# services/addition/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-deployment
  labels:
    app: addition
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addition
  template:
    metadata:
      labels:
        app: addition
    spec:
      containers:
        - name: addition
          image: localhost:5000/webtools/addition:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10