apiVersion: v1
kind: Service
metadata:
  name: traceroute
  namespace: networking
spec:
  selector:
    app: traceroute
  ports:
    - protocol: TCP
      port: 11001
      targetPort: 11001
  type: ClusterIP
