apiVersion: apps/v1
kind: Deployment
metadata:
  name: nslookup
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nslookup
  template:
    metadata:
      labels:
        app: nslookup
    spec:
      containers:
      - name: nslookup
        image: dostuffonline/nslookup:latest
        ports:
        - containerPort: 11002
