apiVersion: v1
kind: Service
metadata:
  name: nslookup
  namespace: networking
spec:
  selector:
    app: nslookup
  ports:
    - protocol: TCP
      port: 11002
      targetPort: 11002
  type: ClusterIP
